In [1]:
import pandas as pd

In [5]:
import opendatasets as od

dataset_url = 'https://www.kaggle.com/mlg-ulb/creditcardfraud?select=creditcard.csv'

od.download(dataset_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: venupodugu
Your Kaggle Key: ········


  2%|█▏                                                                           | 1.00M/66.0M [00:00<00:09, 7.47MB/s]

100%|█████████████████████████████████████████████████████████████████████████████| 66.0M/66.0M [00:04<00:00, 15.9MB/s]


In [40]:
df = pd.read_csv('./creditcardfraud/creditcard.csv', )
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [7]:
df.shape

(284807, 31)

In [8]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
df.isnull().count()

Time      284807
V1        284807
V2        284807
V3        284807
V4        284807
V5        284807
V6        284807
V7        284807
V8        284807
V9        284807
V10       284807
V11       284807
V12       284807
V13       284807
V14       284807
V15       284807
V16       284807
V17       284807
V18       284807
V19       284807
V20       284807
V21       284807
V22       284807
V23       284807
V24       284807
V25       284807
V26       284807
V27       284807
V28       284807
Amount    284807
Class     284807
dtype: int64

In [10]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [41]:
# Extracting Independent and Dependent features

x = df.drop('Class', axis=1)
y = df.Class

In [12]:
x.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V20       V21       V22       V23       V24  \
0  0.098698  0.363787  ...  0.251412 -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...  0.524980  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  
0  0.128539 -0.189115  0.133558 -0.021053  149.62  
1  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3  0.647376 -0.221929  0.062723  0.061458  123.50  
4 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 30 columns]

In [13]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

## Cross Validation Like KFold and Hyperparameter Tuning

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [16]:
log_class = LogisticRegression()
grid = {'C': 10.0**np.arange(-2,3), 'penalty':['l1', 'l2']}
cv = KFold(n_splits=5, shuffle=False, random_state=None)

In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7)

In [18]:
clf = GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
clf.fit(x_train, y_train)

C:\Users\podug\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [20]:
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85248    61]
 [   43    91]]
0.9987828142738434
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85309
           1       0.60      0.68      0.64       134

    accuracy                           1.00     85443
   macro avg       0.80      0.84      0.82     85443
weighted avg       1.00      1.00      1.00     85443



In [21]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train, y_train)

RandomForestClassifier()

In [22]:
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85248    61]
 [   43    91]]
0.9987828142738434
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85309
           1       0.60      0.68      0.64       134

    accuracy                           1.00     85443
   macro avg       0.80      0.84      0.82     85443
weighted avg       1.00      1.00      1.00     85443



In [23]:
y_train.value_counts()

0    199006
1       358
Name: Class, dtype: int64

In [24]:
class_weight = dict({0:1, 1:100})

In [55]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight = class_weight)
classifier.fit(x_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [56]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85294    12]
 [   26   111]]
0.9995552590615966
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.90      0.81      0.85       137

    accuracy                           1.00     85443
   macro avg       0.95      0.91      0.93     85443
weighted avg       1.00      1.00      1.00     85443



## Under Sampling

In [27]:
y_train.value_counts()

0    199006
1       358
Name: Class, dtype: int64

In [57]:
from imblearn.under_sampling import NearMiss
from collections import Counter

ns = NearMiss(0.8)
x_train_ns, y_train_ns = ns.fit_sample(x_train, y_train)
print(f'The number of classes before fit {Counter(y_train)}')
print(f'The number of classes before fit {Counter(y_train_ns)}')

C:\Users\podug\anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


The number of classes before fit Counter({0: 199009, 1: 355})
The number of classes before fit Counter({0: 443, 1: 355})


In [58]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_ns, y_train_ns)

RandomForestClassifier()

In [59]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[75639  9667]
 [    7   130]]
0.8867783200496238
              precision    recall  f1-score   support

           0       1.00      0.89      0.94     85306
           1       0.01      0.95      0.03       137

    accuracy                           0.89     85443
   macro avg       0.51      0.92      0.48     85443
weighted avg       1.00      0.89      0.94     85443



## Over Sampling

In [33]:
from imblearn.over_sampling import RandomOverSampler

In [60]:
os = RandomOverSampler(0.75)
x_train_os, y_train_os = os.fit_sample(x_train, y_train)
print(f'The number of classes before fit {Counter(y_train)}')
print(f'The number of classes before fit {Counter(y_train_os)}')

C:\Users\podug\anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


The number of classes before fit Counter({0: 199009, 1: 355})
The number of classes before fit Counter({0: 199009, 1: 149256})


In [61]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_os, y_train_os)

RandomForestClassifier()

In [62]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85292    14]
 [   24   113]]
0.9995552590615966
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.89      0.82      0.86       137

    accuracy                           1.00     85443
   macro avg       0.94      0.91      0.93     85443
weighted avg       1.00      1.00      1.00     85443



## SMOTETomek

In [63]:
from imblearn.combine import SMOTETomek

sm = SMOTETomek(0.75)
x_train_sm, y_train_sm = sm.fit_sample(x_train, y_train)
print(f'The number of classes before fit {Counter(y_train)}')
print(f'The number of classes before fit {Counter(y_train_sm)}')

C:\Users\podug\anaconda3\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


The number of classes before fit Counter({0: 199009, 1: 355})
The number of classes before fit Counter({0: 198273, 1: 148520})


In [64]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_sm, y_train_sm)

RandomForestClassifier()

In [65]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85281    25]
 [   22   115]]
0.9994499256814484
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.82      0.84      0.83       137

    accuracy                           1.00     85443
   macro avg       0.91      0.92      0.92     85443
weighted avg       1.00      1.00      1.00     85443



## Ensemble Techniques

In [50]:
from imblearn.ensemble import EasyEnsembleClassifier

In [51]:
easy = EasyEnsembleClassifier()
easy.fit(x_train, y_train)

EasyEnsembleClassifier()

In [54]:
y_pred = easy.predict(x_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[82391  2915]
 [    8   129]]
0.9657900588696557
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     85306
           1       0.04      0.94      0.08       137

    accuracy                           0.97     85443
   macro avg       0.52      0.95      0.53     85443
weighted avg       1.00      0.97      0.98     85443

